from typing import Dict, Any, Optional, Union
import json

class Notification:
    """
    Clase modelo simplificada para representar una notificación.
    """
    
    def __init__(self, user_id: int, message: str, read: bool = False, 
                 id: Optional[int] = None):
        """
        Notification constructor.
        
        Args:
            message: notification message
            read: Indicates whether the notification has been read (False by default)
            id: Unique ID of the notification (automatically generated by the DB)
        """
        self.id = id
        self.user_id = user_id
        self.message = message
        self.read = read

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> 'Notification':
        """
        Create a Notification instance from a dictionary.
        
        Args:
            data: Dictionary with notification data
            
        Returns:
            Created Notification object
        """
        user_id = data.get('user_id')
        if user_id is None:
            raise ValueError("user_id is required and cannot be None")
        return cls(
            id=data.get('id'),
            user_id=int(user_id),
            message=data.get('message', ''),
            read=bool(data.get('read', False))
        )
        
    def to_dict(self) -> Dict[str, Any]:
        """
        Converts the Notification object to a dictionary.

        Returns:
            Dictionary with notification data
        """
        return {
            'id': self.id,
            'user_id': self.user_id,
            'message': self.message,
            'read': self.read
        }
    
    @classmethod
    def from_json(cls, json_data: Union[str, bytes]) -> 'Notification':
        """
        Create a Notification instance from a JSON string.
        
        Args:
            json_data: JSON string or bytes containing notification data
            
        Returns:
            Created Notification object
            
        Raises:
            TypeError: If json_data is not string or bytes
            ValueError: If JSON is invalid, empty, or missing required fields
            json.JSONDecodeError: If JSON parsing fails
        """
        # Validate input type
        if not isinstance(json_data, (str, bytes)):
            raise TypeError(f"json_data must be string or bytes, got {type(json_data).__name__}")
        
        # Validate non empty
        if not json_data or (isinstance(json_data, str) and not json_data.strip()):
            raise ValueError("JSON data cannot be empty")
        
        try:
            # Parse JSON to dictionary
            parsed_data = json.loads(json_data)
        except json.JSONDecodeError as e:
            raise ValueError(f"Invalid JSON format: {str(e)}")
        
        # Use the metod from_dict for create notification objet
        return cls.from_dict(parsed_data)

    @property
    def json(self):
        return self.to_dict()
        
    def __str__(self) -> str:
        """
        String representation of the Notification object.

        Returns:
            String with basic notification information
        """
        return f"Notification(id={self.id}, user_id={self.user_id}, message='{self.message[:40]}...', read={self.read})"