class Constants:
    """
    This class contains constants used in the repository.
    """
    CONNECTION_EMPTY_MSG = "Connection is empty"
    CREATE_NOTIFICATION_ERROR = "Error al crear la notificación"
    GET_NOTIFICATION_ERROR = "Error al obtener las notificaciones del usuario {user_id}"
    ORACLE_ERROR = "Error de tipo Oracle al {process} con id {id}"
    CREATE_SUCCESS_MSG = "Notificación con id {id} creada exitosamente"
    DELETE_NOTIFICATION_ERROR = "Error al eliminar la notificación con id {id}"
    NOT_FIND_NOTIFICATIONS_FOR_USER = "No se encontraron notificacones asociadas al usuario {user_id}"
    UPDATE_READ_STATUS_SUCESFULLY = "Actualizadas {rows_affected} notificaciones como leídas"
    UPDATE_READ_STATUS_ERROR = "Error al actualizar el estado de lectura en las notificaciones"
    GET_NOTIFICATION_PROCESS = "obtener notificaciones"
    DELETE_NOTIFICATION_PROCESS = "eliminar notificaciones"
    CREATE_NOTIFICATION_PROCESS = "crear notificaciones"
    UPDATE_NOTIFICATION_PROCESS = "actualizar estado de lectura"
    MULTIPLE = "multiple"
    DELETE_NOTIFICATION_SUCESFULLY = "Notificacion con ID {notification_id} eliminada correctamente."
    NOTIFICATION_NOT_EXIST = "Notificacion con ID {notification_id} no existe."
    BAD_BODY_ERROR = "El cuerpo de la solicitud está vacío o no es JSON válido"
    BODY_EMPTY_ERROR = "No se enviaron datos en la solicitud"
    EXCEPTION_DEFAULT_NAME = "InternalServerError"
    UNEXPECTED_ERROR = "Error inesperado al procesar la solicitud"
    NOTIFICATION_ID_EMPTY = "No se proporcionaron IDs de notificación"
    NOTIFICATION_ID_SHOULD_BE_POSITIVE = "Todos los IDs de notificación deben ser enteros positivos"